#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# workspaces 
bspc monitor primary -d 1 2 3 4 5 6
bspc monitor LVDS-1 -d 7

bspc config focus_follows_pointer true

# borders
bspc config focused_border_color "#44475a"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

#gaps 
bspc config gapless_monocle false
bspc config window_gap 19
#bspc config split_ratio 0.60

#moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#rules
bspc rule -a feh state=floating
bspc rule -a Xfce4-settings-manager state=floating
bspc rule -a openssh-askpass state=floating
bspc rule -a kdeconnect-app state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a vlc state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a spotify desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^4' follow=on

xrdb merge ~/.Xresources &
$HOME/Documentos/Monitores.sh &

# Set wallpaper:
#feh --bg-fill $HOME/Imágenes/fondos/stretched-1920-1080-1155716.png &

# Python script to always initialize with a different wallpaper:
~/.config/bspwm/scripts/launch.sh &

~/.config/polybar/launch.sh & 
picom

